#.travis.yml

language: node_js
node_js:
  - "6.9.5"

branches:
  only:
  - master
  - develop
dist: trusty

addons:
  chrome: stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - npm install

script:
  - npm run test:coverage:single-run
  - npm run lint
  - npm run build:prod

after_success:
  - if [ $TRAVIS_BRANCH == "develop" ];
    then firebase use grensland-site-dev;
    else firebase use --clear;
    fi
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
