#.travis.yml

language: node_js
node_js:
  - "6.9.5"

branches:
  only:
  - master
dist: trusty
node_js:
  - "6.9.5"
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - if [ $TRAVIS_BRANCH == "develop" ];
    then firebase deploy --token $FIREBASE_TOKEN_DEV
    fi
  - if [ $TRAVIS_BRANCH == "master" ];
    then firebase deploy --token $FIREBASE_TOKEN
    fi

notifications:
  email:
    on_failure: change
    on_success: change
